// Code generated by mockery v2.2.1. DO NOT EDIT.

package pkimock

import (
	mock "github.com/stretchr/testify/mock"
	pki "go.pixelfactory.io/needle/internal/services/pki"
)

// CertificateFactory is an autogenerated mock type for the CertificateFactory type
type CertificateFactory struct {
	mock.Mock
}

// Create provides a mock function with given fields: name
func (_m *CertificateFactory) Create(name string) (*pki.Certificate, error) {
	ret := _m.Called(name)

	var r0 *pki.Certificate
	if rf, ok := ret.Get(0).(func(string) *pki.Certificate); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pki.Certificate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
