// Code generated by mockery v2.2.1. DO NOT EDIT.

package pkimock

import (
	mock "github.com/stretchr/testify/mock"
	pki "go.pixelfactory.io/needle/internal/services/pki"
)

// CertificateRepository is an autogenerated mock type for the CertificateRepository type
type CertificateRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: name
func (_m *CertificateRepository) Get(name string) (*pki.Certificate, error) {
	ret := _m.Called(name)

	var r0 *pki.Certificate
	if rf, ok := ret.Get(0).(func(string) *pki.Certificate); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pki.Certificate)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Store provides a mock function with given fields: certificate
func (_m *CertificateRepository) Store(certificate *pki.Certificate) error {
	ret := _m.Called(certificate)

	var r0 error
	if rf, ok := ret.Get(0).(func(*pki.Certificate) error); ok {
		r0 = rf(certificate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
