// Code generated by mockery v2.44.2. DO NOT EDIT.

package pkimock

import (
	mock "github.com/stretchr/testify/mock"
	pki "go.pixelfactory.io/needle/internal/services/pki"
)

// CertificateService is an autogenerated mock type for the CertificateService type
type CertificateService struct {
	mock.Mock
}

// GetOrCreate provides a mock function with given fields: name
func (_m *CertificateService) GetOrCreate(name string) (*pki.Certificate, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetOrCreate")
	}

	var r0 *pki.Certificate
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*pki.Certificate, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *pki.Certificate); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pki.Certificate)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCertificateService creates a new instance of CertificateService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCertificateService(t interface {
	mock.TestingT
	Cleanup(func())
}) *CertificateService {
	mock := &CertificateService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
