// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// CoreDNSServer is an autogenerated mock type for the CoreDNSServer type
type CoreDNSServer struct {
	mock.Mock
}

type CoreDNSServer_Expecter struct {
	mock *mock.Mock
}

func (_m *CoreDNSServer) EXPECT() *CoreDNSServer_Expecter {
	return &CoreDNSServer_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with given fields:
func (_m *CoreDNSServer) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Shutdown provides a mock function with given fields:
func (_m *CoreDNSServer) Shutdown() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CoreDNSServer_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type CoreDNSServer_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *CoreDNSServer_Expecter) Run() *CoreDNSServer_Run_Call {
	return &CoreDNSServer_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *CoreDNSServer_Run_Call) RunCall(run func()) *CoreDNSServer_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CoreDNSServer_Run_Call) Return(_a0 error) *CoreDNSServer_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreDNSServer_Run_Call) RunAndReturn(run func() error) *CoreDNSServer_Run_Call {
	_c.Call.Return(run)
	return _c
}

// CoreDNSServer_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type CoreDNSServer_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
func (_e *CoreDNSServer_Expecter) Shutdown() *CoreDNSServer_Shutdown_Call {
	return &CoreDNSServer_Shutdown_Call{Call: _e.mock.On("Shutdown")}
}

func (_c *CoreDNSServer_Shutdown_Call) Run(run func()) *CoreDNSServer_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *CoreDNSServer_Shutdown_Call) Return(_a0 error) *CoreDNSServer_Shutdown_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *CoreDNSServer_Shutdown_Call) RunAndReturn(run func() error) *CoreDNSServer_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// NewCoreDNSServer creates a new instance of CoreDNSServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoreDNSServer(t interface {
	mock.TestingT
	Cleanup(func())
},
) *CoreDNSServer {
	mock := &CoreDNSServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
