// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// ServerRunner is an autogenerated mock type for the ServerRunner type
type ServerRunner struct {
	mock.Mock
}

type ServerRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *ServerRunner) EXPECT() *ServerRunner_Expecter {
	return &ServerRunner_Expecter{mock: &_m.Mock}
}

// ListenAndServe provides a mock function with given fields:
func (_m *ServerRunner) ListenAndServe() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListenAndServe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// The following line is corrupted and needs to be removed.
// It appears to be a concatenation of multiple lines that should not be here.

// ServerRunner_ListenAndServe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListenAndServe'
type ServerRunner_ListenAndServe_Call struct {
	*mock.Call
}

// ListenAndServe is a helper method to define mock.On call
func (_e *ServerRunner_Expecter) ListenAndServe() *ServerRunner_ListenAndServe_Call {
	return &ServerRunner_ListenAndServe_Call{Call: _e.mock.On("ListenAndServe")}
}

func (_c *ServerRunner_ListenAndServe_Call) Run(run func()) *ServerRunner_ListenAndServe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ServerRunner_ListenAndServe_Call) Return(_a0 error) *ServerRunner_ListenAndServe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ServerRunner_ListenAndServe_Call) RunAndReturn(run func() error) *ServerRunner_ListenAndServe_Call {
	_c.Call.Return(run)
	return _c
}

// NewServerRunner creates a new instance of ServerRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewServerRunner(t interface {
	mock.TestingT
	Cleanup(func())
},
) *ServerRunner {
	mock := &ServerRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
