version: "2"

issues:
  max-same-issues: 50

formatters:
  enable:
    - goimports
    - golines
  settings:
    goimports:
      local-prefixes:
        - go.pixelfactory.io/needle
    golines:
      max-len: 120

linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - copyloopvar
    - depguard
    - dupl
    - durationcheck
    - errcheck
    - errname
    - errorlint
    - gocritic
    - godot
    - gomoddirectives
    - gosec
    - govet
    - ineffassign
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace

  settings:
    depguard:
      rules:
        deprecated:
          files: ["$all"]
          deny:
            - pkg: github.com/golang/protobuf
              desc: Use google.golang.org/protobuf instead
            - pkg: github.com/satori/go.uuid
              desc: Use github.com/google/uuid instead
            - pkg: github.com/gofrs/uuid$
              desc: Use github.com/gofrs/uuid/v5 or later
        non-main files:
          files: ["!**/main.go"]
          deny:
            - pkg: log$
              desc: Use log/slog instead
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      enable-all: true
      disable: [fieldalignment]
      settings:
        shadow:
          strict: true
    nakedret:
      max-func-lines: 0
    revive:
      rules:
        - name: package-comments
          disabled: true

  exclusions:
    warn-unused: true
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - source: "TODO"
        linters: [godot]
      - text: "should have a package comment"
        linters: [revive]
      - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
        linters: [revive]
      - path: '_test\.go'
        linters:
          - bodyclose
          - dupl
          - errcheck
          - gosec
          - noctx
