// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	zapcore "go.uber.org/zap/zapcore"
)

// ErrorLogger is an autogenerated mock type for the ErrorLogger type
type ErrorLogger struct {
	mock.Mock
}

type ErrorLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *ErrorLogger) EXPECT() *ErrorLogger_Expecter {
	return &ErrorLogger_Expecter{mock: &_m.Mock}
}

// Error provides a mock function with given fields: msg, fields
func (_m *ErrorLogger) Error(msg string, fields ...zapcore.Field) {
	var _ca []interface{}
	_ca = append(_ca, msg)
	for _, _a := range fields {
		_ca = append(_ca, _a)
	}
	_m.Called(_ca...)
}

// ErrorLogger_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type ErrorLogger_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - msg string
//   - fields ...zapcore.Field
func (_e *ErrorLogger_Expecter) Error(msg interface{}, fields ...interface{}) *ErrorLogger_Error_Call {
	return &ErrorLogger_Error_Call{Call: _e.mock.On("Error", append([]interface{}{msg}, fields...)...)}
}

func (_c *ErrorLogger_Error_Call) Run(run func(msg string, fields ...zapcore.Field)) *ErrorLogger_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		if len(args) == 0 {
			return
		}
		fieldArgs := make([]zapcore.Field, 0, len(args)-1)
		for _, arg := range args[1:] {
			fieldArgs = append(fieldArgs, arg.(zapcore.Field))
		}
		run(args[0].(string), fieldArgs...)
	})
	return _c
}

func (_c *ErrorLogger_Error_Call) Return() *ErrorLogger_Error_Call {
	_c.Call.Return()
	return _c
}

// Sync provides a mock function with given fields:
func (_m *ErrorLogger) Sync() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ErrorLogger_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type ErrorLogger_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
func (_e *ErrorLogger_Expecter) Sync() *ErrorLogger_Sync_Call {
	return &ErrorLogger_Sync_Call{Call: _e.mock.On("Sync")}
}

func (_c *ErrorLogger_Sync_Call) Run(run func()) *ErrorLogger_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ErrorLogger_Sync_Call) Return(_a0 error) *ErrorLogger_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ErrorLogger_Sync_Call) RunAndReturn(run func() error) *ErrorLogger_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// NewErrorLogger creates a new instance of ErrorLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewErrorLogger(t interface {
	mock.TestingT
	Cleanup(func())
},
) *ErrorLogger {
	mock := &ErrorLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
