// Code generated by mockery v2.45.1. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	pki "go.pixelfactory.io/needle/internal/app/pki"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

type Repository_Expecter struct {
	mock *mock.Mock
}

func (_m *Repository) EXPECT() *Repository_Expecter {
	return &Repository_Expecter{mock: &_m.Mock}
}

// Get provides a mock function with given fields: name
func (_m *Repository) Get(name string) (*pki.InternalCert, error) {
	ret := _m.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *pki.InternalCert
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*pki.InternalCert, error)); ok {
		return rf(name)
	}
	if rf, ok := ret.Get(0).(func(string) *pki.InternalCert); ok {
		r0 = rf(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pki.InternalCert)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(name)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Repository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type Repository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - name string
func (_e *Repository_Expecter) Get(name interface{}) *Repository_Get_Call {
	return &Repository_Get_Call{Call: _e.mock.On("Get", name)}
}

func (_c *Repository_Get_Call) Run(run func(name string)) *Repository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *Repository_Get_Call) Return(_a0 *pki.InternalCert, _a1 error) *Repository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Repository_Get_Call) RunAndReturn(run func(string) (*pki.InternalCert, error)) *Repository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: certificate
func (_m *Repository) Store(certificate *pki.InternalCert) error {
	ret := _m.Called(certificate)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*pki.InternalCert) error); ok {
		r0 = rf(certificate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Repository_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type Repository_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - certificate *pki.InternalCert
func (_e *Repository_Expecter) Store(certificate interface{}) *Repository_Store_Call {
	return &Repository_Store_Call{Call: _e.mock.On("Store", certificate)}
}

func (_c *Repository_Store_Call) Run(run func(certificate *pki.InternalCert)) *Repository_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*pki.InternalCert))
	})
	return _c
}

func (_c *Repository_Store_Call) Return(_a0 error) *Repository_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Repository_Store_Call) RunAndReturn(run func(*pki.InternalCert) error) *Repository_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
