on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.21.x

      - name: Install step-cli
        run: |
          wget -q -P /tmp https://github.com/smallstep/cli/releases/download/v0.27.2/step-cli_0.27.2_amd64.deb
          sudo dpkg -i /tmp/step-cli_0.27.2_amd64.deb

      - name: Run gofmt
        run: make gofmt

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3

      - name: Run go test
        run: make ca-test cert-test test

      - uses: codecov/codecov-action@v4
        with:
          fail_ci_if_error: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
